spring.application.name=ebanking-backend
server.port=8085

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:ebankingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Configuration
jwt.secret=p9Z2n8Wv4XkL7mRq5TjB3fN1sY6hD9gK4vP2xM8zL0rS7tW3nQ6bV1cX5yJ8eH4a

# Gemini Configuration
spring.ai.vertex.ai.gemini.api-key=AIzaSyCMTjrbi9Apk_h4Tprsn9in69l_isfWEPU
spring.ai.vertex.ai.gemini.project-id=602650663668
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-1.5-flash
spring.ai.vertex.ai.gemini.transport=rest

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html