spring.application.name=ebanking-backend
server.port=8086

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/E-BANK?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=p9Z2n8Wv4XkL7mRq5TjB3fN1sY6hD9gK4vP2xM8zL0rS7tW3nQ6bV1cX5yJ8eH4a

# Gemini Configuration
spring.ai.vertex.ai.gemini.api-key=AIzaSyCMTjrbi9Apk_h4Tprsn9in69l_isfWEPU
spring.ai.vertex.ai.gemini.project-id=602650663668
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-1.5-flash
spring.ai.vertex.ai.gemini.transport=rest

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html